language: perl

install:
  - bash .travis-install-system.sh
  - cpanm -n Acme::Alien::DontPanic
  - cpanm -n FFI::Platypus

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

script:
  - perl Build.PL
  - ./Build
  - ./Build test
  - ./Build install

env:
  - ALIEN_FORCE=0 PATH=$PATH:$HOME/travislocal/bin LD_LIBRARY_PATH=$HOME/travislocal/lib PKG_CONFIG_PATH=$HOME/travislocal/lib/pkgconfig
  - ALIEN_FORCE=1

sudo: false
