---
abstract: 'FFI test for Alien::Base'
author:
  - 'Graham Ollis <plicease@wdlabs.com>'
build_requires:
  ExtUtils::CBuilder: '0'
configure_requires:
  Acme::Alien::DontPanic: '0.022'
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Ford-Prefect-FFI
provides:
  Acme::Ford::Prefect::FFI:
    file: lib/Acme/Ford/Prefect/FFI.pm
    version: '0.19'
requires:
  Acme::Alien::DontPanic: '0.022'
  FFI::CheckLib: '0.11'
  FFI::Platypus: '0.08'
  perl: '5.008001'
resources:
  bugtracker: http://github.com/plicease/Acme-Ford-Prefect-FFI/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/plicease/Acme-Ford-Prefect-FFI
version: '0.19'
